# Generated by Django 3.0.7 on 2020-06-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_bot_reply',
            field=models.BooleanField(default=False),
        ),
    ]
